version: '3'
services:
  frontend:
    image: nginx:stable
    ports:
      - "8000:8000"
    links:
      - backend
    volumes:
      - ./memory-matching-client/build:/var/www:ro
      - ./client/conf.d/app.conf:/etc/nginx/nginx.conf:ro

  backend:
    restart: always
    image: project/todo-app
    ports:
      - 8080:8080
    depends_on:
      - docker-postgres

  docker-postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
